### ISSUE TITLE
The app doesn't work unless I clear localstorage

### ISSUE THREAD

**Issue by felixls** [tzbutton/tzbutton#11]
At the first try the app works great, then the next time you try to click again it doesn't connect to the wallet anymore.

So, the only way I found was to go to dev console "Clear storage" and then click in "Clear site data"

**Comment by AndreasGassmann** [comment]
Hi, thanks for the report.

Which wallet are you using? We had another report that it doesn't work a second time when using Kukai. I tried to reproduce it with the Beacon Extension, but it seemed to work (I didn't actually didn't inject the tx, but I don't think that would influence it).

**Comment by AndreasGassmann** [comment]
I just pushed a change. I made some improvements to the "reconnect" behaviour. It should now only ask for permissions the first time, and reconnecting to p2p wallets should work now.

Can you try again and let me know if it works?

**Comment by felixls** [comment]
Thanks for your answer, I was using Kukai, I tested again and has the same problem

**Comment by AndreasGassmann** [comment]
Did you make sure to refresh the page before trying? Because I was in contact with the developer of Kukai (he was the one initially reporting the problem) and he confirmed that the problem has been fixed.

**Comment by felixls** [comment]
here a screen recording with the problem

https://user-images.githubusercontent.com/2390220/102809516-057d2e00-43ba-11eb-9109-9fb71e8cbecc.mp4


Browser: Brave version 1.17.75 Chromium: 87.0.4280.88 (Official Build) unknown (64-bit)
OS: Arch linux

**Comment by AndreasGassmann** [comment]
Do you have Kukai open in another Tab? Because after the initial pairing, then the DApp is no longer opening another Tab. It sends the data over the now established p2p connection, so if you have Kukai open in another Tab, it should trigger the request.

**Comment by felixls** [comment]
Yes, that worked, but I had to enter in the kukai account e.g.: https://wallet.kukai.app/account/tz2....   (it doesn't work if you are in https://wallet.kukai.app/accounts). 

Also tzButton doesn't say something like "request issued, check Kukai wallet in the other page" or something like that, which makes the behavior not user friendly

**Comment by AndreasGassmann** [comment]
> Yes, that worked, but I had to enter in the kukai account e.g.: https://wallet.kukai.app/account/tz2.... (it doesn't work if you are in https://wallet.kukai.app/accounts).

I'll ping @klassare, the maintainer of Kukai wallet for this one.

> Also tzButton doesn't say something like "request issued, check Kukai wallet in the other page" or something like that, which makes the behavior not user friendly

We're aware of that and are currently working on a better flow in the underlying library we use: https://github.com/airgap-it/beacon-sdk/issues/83

**Comment by klassare** [comment]
> Yes, that worked, but I had to enter in the kukai account e.g.: https://wallet.kukai.app/account/tz2.... (it doesn't work if you are in https://wallet.kukai.app/accounts).
> 
It shouldn't matter what page you are on as long as you're logged in. Was not able to reproduce this with the Brave browser. Must be another reason why it didn't work at first.
