### ISSUE TITLE
How to: "counting down from 21 hours and 45 minutes"?

### ISSUE THREAD

**Issue by denver-s** [tzbutton/tzbutton#3]
> 5 hours and 32 minutes before the countdown expires, Charlie presses the button, 2420 XTZ are now on the smart contract, the countdown is reset and the **total time is reduced by 1 minutes, which means it's now counting down from 21 hours and 45 minutes.**

Why 21 hours and 45 minutes? I don't get what's the logic behind the reduction of total time.

https://github.com/tzbutton/tzbutton/blob/ce99057fb1a924eb3e8070fb0f5527d687426a27/src/components/HowTo/HowTo.tsx#L89

**Comment by AndreasGassmann** [comment]
Good catch, that's a copy paste mistake. I'll fix it right away.
